# GitHub Actions Workflow Template for Microservices
# Шаблон для создания CI/CD workflows для микросервисов

name: "{{ SERVICE_NAME }} CI/CD"

on:
  push:
    branches: [ main, develop, "release/*" ]
    paths:
      - "services/{{ service_name }}/**"
      - "shared/**"
      - "!.github/workflows/{{ service_name }}.yml"
  
  pull_request:
    branches: [ main, develop ]
    paths:
      - "services/{{ service_name }}/**"
      - "shared/**"
  
  # Manual triggers
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      
      skip_tests:
        description: "Skip quality gates (emergency only)"
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Code Quality and Security
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'services/{{ service_name }}/package-lock.json'

      - name: Install dependencies
        run: |
          cd services/{{ service_name }}
          npm ci --only=production
          npm ci --only=dev

      - name: ESLint
        run: |
          cd services/{{ service_name }}
          npx eslint src/ --format=json --output-file=../../reports/eslint-{{ service_name }}.json
          npx eslint src/ || true

      - name: Prettier check
        run: |
          cd services/{{ service_name }}
          npx prettier --check src/

      - name: TypeScript check
        run: |
          cd services/{{ service_name }}
          npx tsc --noEmit

      - name: Security audit
        run: |
          cd services/{{ service_name }}
          npm audit --audit-level=moderate --json > ../../reports/npm-audit-{{ service_name }}.json || true

      - name: Upload quality reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: quality-reports
          path: reports/
          retention-days: 30

  # Tests
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: quality-gates
    
    strategy:
      matrix:
        test-type: [unit, integration, e2e]
        node-version: [18, 20]
        exclude:
          # Упрощенная матрица для PR
          - test-type: e2e
            pull_request: ${{ github.event_name == 'pull_request' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'services/{{ service_name }}/package-lock.json'

      - name: Install dependencies
        run: |
          cd services/{{ service_name }}
          npm ci --only=production
          npm ci --only=dev

      - name: Run tests
        run: |
          cd services/{{ service_name }}
          case ${{ matrix.test-type }} in
            unit)
              npm run test:unit -- --coverage --coverageReporters=lcov --coverageReporters=json
              ;;
            integration)
              npm run test:integration -- --coverage --coverageReporters=json
              ;;
            e2e)
              npx playwright test --reporter=json
              ;;
          esac

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.test-type }}-${{ matrix.node-version }}
          path: |
            services/{{ service_name }}/coverage/
            services/{{ service_name }}/test-results/
          retention-days: 30

  # Security Scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: quality-gates
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json --file=services/{{ service_name }}/package.json

      - name: Upload Snyk results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-scan
          path: snyk*.json
          retention-days: 30

  # Build and Push Docker Image
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [quality-gates, tests, security-scan]
    if: always() && needs.quality-gates.result == 'success'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/{{ service_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/{{ service_name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.ref_name }}

      - name: Security Scan Built Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/{{ service_name }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-{{ service_name }}.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-{{ service_name }}.sarif'

  # Deploy to Environment
  deploy:
    name: Deploy to {{ ENVIRONMENT | default('staging') }}
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.event.inputs.environment
    environment: {{ ENVIRONMENT | default('staging') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          
          # Применение Kubernetes манифестов
          envsubst < services/{{ service_name }}/k8s/deployment.yaml | kubectl apply -f -
          envsubst < services/{{ service_name }}/k8s/service.yaml | kubectl apply -f -
          
          # Ожидание готовности
          kubectl rollout status deployment/{{ service_name }} --timeout=300s

      - name: Health Check
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          
          # Получение endpoint
          SERVICE_IP=$(kubectl get svc {{ service_name }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || kubectl get svc {{ service_name }} -o jsonpath='{.spec.clusterIP}')
          
          # Health check
          curl -f "http://$SERVICE_IP/health" || exit 1
          
          # API status check
          curl -f "http://$SERVICE_IP/api/v1/status" || exit 1

      - name: Run Smoke Tests
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          
          # Установка dependencies для smoke тестов
          npm install -g @playwright/test
          
          # Запуск smoke тестов
          cd tests/smoke
          npx playwright test {{ service_name }}.spec.ts --baseUrl="http://$(kubectl get svc {{ service_name }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || kubectl get svc {{ service_name }} -o jsonpath='{.spec.clusterIP}')"

      - name: Notify deployment
        if: success()
        run: |
          # Slack notification
          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"🚀 {{ service_name }} deployed successfully to {{ ENVIRONMENT | default('staging') }}\"}" \
              ${{ secrets.SLACK_WEBHOOK_URL }}
          fi

  # Rollback (Emergency)
  rollback:
    name: Emergency Rollback
    runs-on: ubuntu-latest
    needs: [deploy]
    if: failure() && needs.deploy.result == 'failure'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Rollback deployment
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          
          kubectl rollout undo deployment/{{ service_name }}
          kubectl rollout status deployment/{{ service_name }} --timeout=300s

      - name: Notify rollback
        run: |
          # Slack notification
          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"⚠️ Emergency rollback executed for {{ service_name }}\"}" \
              ${{ secrets.SLACK_WEBHOOK_URL }}
          fi

  # Cleanup
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [deploy, rollback]
    if: always()
    
    steps:
      - name: Cleanup temporary files
        run: |
          rm -f kubeconfig
          rm -f reports/*.json

      - name: Upload final reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: final-reports
          path: |
            reports/
          retention-days: 90