# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import ai_service_pb2 as ai__service__pb2
import grpc

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIOrchestratorStub(object):
    """Сервис AI Orchestrator для обработки запросов к AI
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessQuery = channel.unary_unary(
                '/ai_service.AIOrchestrator/ProcessQuery',
                request_serializer=ai__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=ai__service__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.StreamQuery = channel.unary_stream(
                '/ai_service.AIOrchestrator/StreamQuery',
                request_serializer=ai__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=ai__service__pb2.QueryChunk.FromString,
                _registered_method=True)
        self.StreamScreenContext = channel.stream_stream(
                '/ai_service.AIOrchestrator/StreamScreenContext',
                request_serializer=ai__service__pb2.ScreenFrame.SerializeToString,
                response_deserializer=ai__service__pb2.ContextAnalysis.FromString,
                _registered_method=True)


class AIOrchestratorServicer(object):
    """Сервис AI Orchestrator для обработки запросов к AI
    """

    def ProcessQuery(self, request, context):
        """Простой запрос-ответ к AI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuery(self, request, context):
        """Стриминг ответа для длинных генераций
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamScreenContext(self, request_iterator, context):
        """Двунаправленный стрим для анализа экрана в реальном времени
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIOrchestratorServicer_to_server(servicer, server):
        """TODO: Описать функцию add_AIOrchestratorServicer_to_server.
                
                Args:
                    servicer: TODO: Описать параметр.
                    server: TODO: Описать параметр.
                """    rpc_method_handlers = {
            'ProcessQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessQuery,
                    request_deserializer=ai__service__pb2.QueryRequest.FromString,
                    response_serializer=ai__service__pb2.QueryResponse.SerializeToString,
            ),
            'StreamQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamQuery,
                    request_deserializer=ai__service__pb2.QueryRequest.FromString,
                    response_serializer=ai__service__pb2.QueryChunk.SerializeToString,
            ),
            'StreamScreenContext': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamScreenContext,
                    request_deserializer=ai__service__pb2.ScreenFrame.FromString,
                    response_serializer=ai__service__pb2.ContextAnalysis.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AIOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'ai_service.AIOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIOrchestrator(object):
    """Сервис AI Orchestrator для обработки запросов к AI
    """

    @staticmethod
    def ProcessQuery(request,
                """TODO: Описать функцию ProcessQuery.
                        
                        Args:
                            request: TODO: Описать параметр.
                            target: TODO: Описать параметр.
                            options: TODO: Описать параметр.
                            channel_credentials: TODO: Описать параметр.
                            call_credentials: TODO: Описать параметр.
                            insecure: TODO: Описать параметр.
                            compression: TODO: Описать параметр.
                            wait_for_ready: TODO: Описать параметр.
                            timeout: TODO: Описать параметр.
                            metadata: TODO: Описать параметр.
                        """            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIOrchestrator/ProcessQuery',
            ai__service__pb2.QueryRequest.SerializeToString,
            ai__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQuery(request,
                """TODO: Описать функцию StreamQuery.
                        
                        Args:
                            request: TODO: Описать параметр.
                            target: TODO: Описать параметр.
                            options: TODO: Описать параметр.
                            channel_credentials: TODO: Описать параметр.
                            call_credentials: TODO: Описать параметр.
                            insecure: TODO: Описать параметр.
                            compression: TODO: Описать параметр.
                            wait_for_ready: TODO: Описать параметр.
                            timeout: TODO: Описать параметр.
                            metadata: TODO: Описать параметр.
                        """            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_service.AIOrchestrator/StreamQuery',
            ai__service__pb2.QueryRequest.SerializeToString,
            ai__service__pb2.QueryChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamScreenContext(request_iterator,
                """TODO: Описать функцию StreamScreenContext.
                        
                        Args:
                            request_iterator: TODO: Описать параметр.
                            target: TODO: Описать параметр.
                            options: TODO: Описать параметр.
                            channel_credentials: TODO: Описать параметр.
                            call_credentials: TODO: Описать параметр.
                            insecure: TODO: Описать параметр.
                            compression: TODO: Описать параметр.
                            wait_for_ready: TODO: Описать параметр.
                            timeout: TODO: Описать параметр.
                            metadata: TODO: Описать параметр.
                        """            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai_service.AIOrchestrator/StreamScreenContext',
            ai__service__pb2.ScreenFrame.SerializeToString,
            ai__service__pb2.ContextAnalysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CodeGraphServiceStub(object):
    """Сервис для работы с графом кода 1С
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchCode = channel.unary_unary(
                '/ai_service.CodeGraphService/SearchCode',
                request_serializer=ai__service__pb2.CodeSearchRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CodeSearchResponse.FromString,
                _registered_method=True)
        self.AnalyzeDependencies = channel.unary_unary(
                '/ai_service.CodeGraphService/AnalyzeDependencies',
                request_serializer=ai__service__pb2.DependencyRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DependencyResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/ai_service.CodeGraphService/GetMetadata',
                request_serializer=ai__service__pb2.MetadataRequest.SerializeToString,
                response_deserializer=ai__service__pb2.MetadataResponse.FromString,
                _registered_method=True)


class CodeGraphServiceServicer(object):
    """Сервис для работы с графом кода 1С
    """

    def SearchCode(self, request, context):
        """Семантический поиск по коду
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeDependencies(self, request, context):
        """Анализ зависимостей модулей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Получить метаданные объекта 1С
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeGraphServiceServicer_to_server(servicer, server):
        """TODO: Описать функцию add_CodeGraphServiceServicer_to_server.
                
                Args:
                    servicer: TODO: Описать параметр.
                    server: TODO: Описать параметр.
                """    rpc_method_handlers = {
            'SearchCode': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCode,
                    request_deserializer=ai__service__pb2.CodeSearchRequest.FromString,
                    response_serializer=ai__service__pb2.CodeSearchResponse.SerializeToString,
            ),
            'AnalyzeDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDependencies,
                    request_deserializer=ai__service__pb2.DependencyRequest.FromString,
                    response_serializer=ai__service__pb2.DependencyResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=ai__service__pb2.MetadataRequest.FromString,
                    response_serializer=ai__service__pb2.MetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.CodeGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'ai_service.CodeGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeGraphService(object):
    """Сервис для работы с графом кода 1С
    """

    @staticmethod
    def SearchCode(request,
                """TODO: Описать функцию SearchCode.
                        
                        Args:
                            request: TODO: Описать параметр.
                            target: TODO: Описать параметр.
                            options: TODO: Описать параметр.
                            channel_credentials: TODO: Описать параметр.
                            call_credentials: TODO: Описать параметр.
                            insecure: TODO: Описать параметр.
                            compression: TODO: Описать параметр.
                            wait_for_ready: TODO: Описать параметр.
                            timeout: TODO: Описать параметр.
                            metadata: TODO: Описать параметр.
                        """            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.CodeGraphService/SearchCode',
            ai__service__pb2.CodeSearchRequest.SerializeToString,
            ai__service__pb2.CodeSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeDependencies(request,
                """TODO: Описать функцию AnalyzeDependencies.
                        
                        Args:
                            request: TODO: Описать параметр.
                            target: TODO: Описать параметр.
                            options: TODO: Описать параметр.
                            channel_credentials: TODO: Описать параметр.
                            call_credentials: TODO: Описать параметр.
                            insecure: TODO: Описать параметр.
                            compression: TODO: Описать параметр.
                            wait_for_ready: TODO: Описать параметр.
                            timeout: TODO: Описать параметр.
                            metadata: TODO: Описать параметр.
                        """            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.CodeGraphService/AnalyzeDependencies',
            ai__service__pb2.DependencyRequest.SerializeToString,
            ai__service__pb2.DependencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
                """TODO: Описать функцию GetMetadata.
                        
                        Args:
                            request: TODO: Описать параметр.
                            target: TODO: Описать параметр.
                            options: TODO: Описать параметр.
                            channel_credentials: TODO: Описать параметр.
                            call_credentials: TODO: Описать параметр.
                            insecure: TODO: Описать параметр.
                            compression: TODO: Описать параметр.
                            wait_for_ready: TODO: Описать параметр.
                            timeout: TODO: Описать параметр.
                            metadata: TODO: Описать параметр.
                        """            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.CodeGraphService/GetMetadata',
            ai__service__pb2.MetadataRequest.SerializeToString,
            ai__service__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ScenarioServiceStub(object):
    """Сервис для работы со сценариями
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendations = channel.unary_unary(
                '/ai_service.ScenarioService/GetRecommendations',
                request_serializer=ai__service__pb2.ScenarioRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ScenarioResponse.FromString,
                _registered_method=True)
        self.ExecuteScenario = channel.unary_stream(
                '/ai_service.ScenarioService/ExecuteScenario',
                request_serializer=ai__service__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ExecutionStatus.FromString,
                _registered_method=True)


class ScenarioServiceServicer(object):
    """Сервис для работы со сценариями
    """

    def GetRecommendations(self, request, context):
        """Получить рекомендуемые сценарии на основе контекста
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScenario(self, request, context):
        """Выполнить сценарий с отслеживанием прогресса
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScenarioServiceServicer_to_server(servicer, server):
        """TODO: Описать функцию add_ScenarioServiceServicer_to_server.
                
                Args:
                    servicer: TODO: Описать параметр.
                    server: TODO: Описать параметр.
                """    rpc_method_handlers = {
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=ai__service__pb2.ScenarioRequest.FromString,
                    response_serializer=ai__service__pb2.ScenarioResponse.SerializeToString,
            ),
            'ExecuteScenario': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteScenario,
                    request_deserializer=ai__service__pb2.ExecuteRequest.FromString,
                    response_serializer=ai__service__pb2.ExecutionStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.ScenarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'ai_service.ScenarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScenarioService(object):
    """Сервис для работы со сценариями
    """

    @staticmethod
    def GetRecommendations(request,
                """TODO: Описать функцию GetRecommendations.
                        
                        Args:
                            request: TODO: Описать параметр.
                            target: TODO: Описать параметр.
                            options: TODO: Описать параметр.
                            channel_credentials: TODO: Описать параметр.
                            call_credentials: TODO: Описать параметр.
                            insecure: TODO: Описать параметр.
                            compression: TODO: Описать параметр.
                            wait_for_ready: TODO: Описать параметр.
                            timeout: TODO: Описать параметр.
                            metadata: TODO: Описать параметр.
                        """            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.ScenarioService/GetRecommendations',
            ai__service__pb2.ScenarioRequest.SerializeToString,
            ai__service__pb2.ScenarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteScenario(request,
                """TODO: Описать функцию ExecuteScenario.
                        
                        Args:
                            request: TODO: Описать параметр.
                            target: TODO: Описать параметр.
                            options: TODO: Описать параметр.
                            channel_credentials: TODO: Описать параметр.
                            call_credentials: TODO: Описать параметр.
                            insecure: TODO: Описать параметр.
                            compression: TODO: Описать параметр.
                            wait_for_ready: TODO: Описать параметр.
                            timeout: TODO: Описать параметр.
                            metadata: TODO: Описать параметр.
                        """            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_service.ScenarioService/ExecuteScenario',
            ai__service__pb2.ExecuteRequest.SerializeToString,
            ai__service__pb2.ExecutionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
